image: gradle:8-jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dhttps.proxyHost=194.254.199.96 -Dhttps.proxyPort=3128"

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  image: gradle:8.3.0-jdk17
  script:
    - ./gradlew shadowJar
  only:
    - master
    - develop